export const famousFootballPlayers = [
  'Lionel Messi',
  'Pelé',
  'Diego Maradona',
  'Cristiano Ronaldo',
  'Johan Cruyff',
  'Zinedine Zidane',
  'Franz Beckenbauer',
  'Ronaldo Nazário',
  'George Best',
  'Ronaldinho',
  'Paolo Maldini',
  'Michel Platini',
  'Alfredo Di Stéfano',
  'Ferenc Puskás',
  'Garrincha',
  'Eusébio',
  'Bobby Charlton',
  'Giuseppe Meazza',
  'Lev Yashin',
  'Marco van Basten',
  'Andrés Iniesta',
  'Neymar Jr',
  'Kylian Mbappé',
  'Thierry Henry',
  'Xavi Hernández',
  'Andrea Pirlo',
  'Sergio Ramos',
  'Carles Puyol',
  'George Weah',
  'Kaká',
  'Stanley Matthews',
  'Gareth Bale',
  'Zico',
  'Lothar Matthäus',
  'Ruud Gullit',
  'Didi',
  'Gianni Rivera',
  'Raymond Kopa',
  'Zizinho',
  'Roberto Baggio',
  'Dennis Bergkamp',
  'Rivaldo',
  'Romário',
  'Gabriel Batistuta',
  'Ángel Di María',
  'Marcelo',
  'Juan Román Riquelme',
  'Hernán Crespo',
  'Luis Suárez',
  'Dani Alves',
  'Jay-Jay Okocha',
  'Eden Hazard',
  'Arjen Robben',
  'Franck Ribéry',
  'Ousmane Dembélé',
  'Gianfranco Zola',
  'Erling Haaland',
  'Lamine Yamal',
  'Jude Bellingham',
  'Kevin De Bruyne',
  'Son Heung-min',
  'Mohamed Salah',
  'Didier Drogba',
  'Yaya Touré',
  'Robin van Persie',
  'Radamel Falcao',
  'Ashley Cole',
  'Wayne Rooney',
  'Joe Hart',
  'John Terry',
  'Javier Zanetti',
  'Stephan El Shaarawy',
  'Djalma Santos',
  'Nílton Santos',
  'Philipp Lahm',
  'Roberto Carlos',
  'Cafu',
  'Gerd Müller',
  'Franz Platini',
  'Bobby Moore',
  'Franco Baresi',
  'Alessandro Nesta',
  'Raul González',
  'David Beckham',
  'Steven Gerrard',
  'Frank Lampard',
  'Paul Scholes',
  'Patrick Vieira',
  'Clarence Seedorf',
  'Michael Laudrup',
  'Eric Cantona',
  'Peter Schmeichel',
  'Alan Shearer',
  'Hristo Stoichkov',
  'Luis Figo',
  'Ryan Giggs',
  "Samuel Eto'o",
  'Robert Lewandowski',
  'Vinícius Júnior',
];
